/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FNFT } from "./FNFT";
export type { LockFarm } from "./LockFarm";
export type { VotingFarm } from "./VotingFarm";
