/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface VotingFarmInterface extends utils.Interface {
  functions: {
    "HEC()": FunctionFragment;
    "addFarmForOwner(address)": FunctionFragment;
    "admin()": FunctionFragment;
    "canVote()": FunctionFragment;
    "deprecateFarm(address)": FunctionFragment;
    "fNFT()": FunctionFragment;
    "farmStatus(address)": FunctionFragment;
    "farmVote(address,uint256)": FunctionFragment;
    "farmWeights(address)": FunctionFragment;
    "getFarms()": FunctionFragment;
    "getFarmsLength()": FunctionFragment;
    "getFarmsWeights()": FunctionFragment;
    "getWeightByUser(address)": FunctionFragment;
    "lastVote(address)": FunctionFragment;
    "length()": FunctionFragment;
    "lockFarm()": FunctionFragment;
    "maxPercentage()": FunctionFragment;
    "reset()": FunctionFragment;
    "resurrectFarm(address)": FunctionFragment;
    "revote(address)": FunctionFragment;
    "setAdmin(address)": FunctionFragment;
    "setConfiguration(address,address,address)": FunctionFragment;
    "setMaxPercentageFarm(uint256)": FunctionFragment;
    "setTestMode()": FunctionFragment;
    "totalWeight()": FunctionFragment;
    "usedWeights(address)": FunctionFragment;
    "vote(address[],uint256[])": FunctionFragment;
    "voteDelay()": FunctionFragment;
    "votes(address,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "HEC"
      | "addFarmForOwner"
      | "admin"
      | "canVote"
      | "deprecateFarm"
      | "fNFT"
      | "farmStatus"
      | "farmVote"
      | "farmWeights"
      | "getFarms"
      | "getFarmsLength"
      | "getFarmsWeights"
      | "getWeightByUser"
      | "lastVote"
      | "length"
      | "lockFarm"
      | "maxPercentage"
      | "reset"
      | "resurrectFarm"
      | "revote"
      | "setAdmin"
      | "setConfiguration"
      | "setMaxPercentageFarm"
      | "setTestMode"
      | "totalWeight"
      | "usedWeights"
      | "vote"
      | "voteDelay"
      | "votes"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "HEC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addFarmForOwner",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(functionFragment: "canVote", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deprecateFarm",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "fNFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "farmStatus",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "farmVote",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "farmWeights",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "getFarms", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getFarmsLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFarmsWeights",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWeightByUser",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "lastVote",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "length", values?: undefined): string;
  encodeFunctionData(functionFragment: "lockFarm", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "reset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "resurrectFarm",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "revote",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setConfiguration",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxPercentageFarm",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setTestMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalWeight",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "usedWeights",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [PromiseOrValue<string>[], PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(functionFragment: "voteDelay", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "votes",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "HEC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addFarmForOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deprecateFarm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fNFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "farmStatus", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "farmVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "farmWeights",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFarms", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFarmsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFarmsWeights",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWeightByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lastVote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "length", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lockFarm", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resurrectFarm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxPercentageFarm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTestMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usedWeights",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voteDelay", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "votes", data: BytesLike): Result;

  events: {
    "FarmAddedByOwner(address)": EventFragment;
    "FarmDeprecated(address)": EventFragment;
    "FarmResurrected(address)": EventFragment;
    "FarmVoted(address)": EventFragment;
    "SetAdmin(address,address)": EventFragment;
    "SetConfiguration(address)": EventFragment;
    "SetMaxPercentageFarm(uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FarmAddedByOwner"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FarmDeprecated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FarmResurrected"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FarmVoted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetAdmin"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetConfiguration"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetMaxPercentageFarm"): EventFragment;
}

export interface FarmAddedByOwnerEventObject {
  farm: string;
}
export type FarmAddedByOwnerEvent = TypedEvent<
  [string],
  FarmAddedByOwnerEventObject
>;

export type FarmAddedByOwnerEventFilter =
  TypedEventFilter<FarmAddedByOwnerEvent>;

export interface FarmDeprecatedEventObject {
  farm: string;
}
export type FarmDeprecatedEvent = TypedEvent<
  [string],
  FarmDeprecatedEventObject
>;

export type FarmDeprecatedEventFilter = TypedEventFilter<FarmDeprecatedEvent>;

export interface FarmResurrectedEventObject {
  farm: string;
}
export type FarmResurrectedEvent = TypedEvent<
  [string],
  FarmResurrectedEventObject
>;

export type FarmResurrectedEventFilter = TypedEventFilter<FarmResurrectedEvent>;

export interface FarmVotedEventObject {
  owner: string;
}
export type FarmVotedEvent = TypedEvent<[string], FarmVotedEventObject>;

export type FarmVotedEventFilter = TypedEventFilter<FarmVotedEvent>;

export interface SetAdminEventObject {
  oldAdmin: string;
  newAdmin: string;
}
export type SetAdminEvent = TypedEvent<[string, string], SetAdminEventObject>;

export type SetAdminEventFilter = TypedEventFilter<SetAdminEvent>;

export interface SetConfigurationEventObject {
  admin: string;
}
export type SetConfigurationEvent = TypedEvent<
  [string],
  SetConfigurationEventObject
>;

export type SetConfigurationEventFilter =
  TypedEventFilter<SetConfigurationEvent>;

export interface SetMaxPercentageFarmEventObject {
  percentage: BigNumber;
  admin: string;
}
export type SetMaxPercentageFarmEvent = TypedEvent<
  [BigNumber, string],
  SetMaxPercentageFarmEventObject
>;

export type SetMaxPercentageFarmEventFilter =
  TypedEventFilter<SetMaxPercentageFarmEvent>;

export interface VotingFarm extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VotingFarmInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    HEC(overrides?: CallOverrides): Promise<[string]>;

    addFarmForOwner(
      _farm: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    admin(overrides?: CallOverrides): Promise<[string]>;

    canVote(overrides?: CallOverrides): Promise<[boolean]>;

    deprecateFarm(
      _farm: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    fNFT(overrides?: CallOverrides): Promise<[string]>;

    farmStatus(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    farmVote(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    farmWeights(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getFarms(overrides?: CallOverrides): Promise<[string[]]>;

    getFarmsLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    getFarmsWeights(overrides?: CallOverrides): Promise<[BigNumber[]]>;

    getWeightByUser(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    lastVote(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    length(overrides?: CallOverrides): Promise<[BigNumber]>;

    lockFarm(overrides?: CallOverrides): Promise<[string]>;

    maxPercentage(overrides?: CallOverrides): Promise<[BigNumber]>;

    reset(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    resurrectFarm(
      _farm: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revote(
      _owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setAdmin(
      _admin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setConfiguration(
      _fnft: PromiseOrValue<string>,
      _hec: PromiseOrValue<string>,
      _lockFarm: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMaxPercentageFarm(
      _percentage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setTestMode(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    totalWeight(overrides?: CallOverrides): Promise<[BigNumber]>;

    usedWeights(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    vote(
      _farmVote: PromiseOrValue<string>[],
      _weights: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    voteDelay(overrides?: CallOverrides): Promise<[BigNumber]>;

    votes(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  HEC(overrides?: CallOverrides): Promise<string>;

  addFarmForOwner(
    _farm: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  admin(overrides?: CallOverrides): Promise<string>;

  canVote(overrides?: CallOverrides): Promise<boolean>;

  deprecateFarm(
    _farm: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  fNFT(overrides?: CallOverrides): Promise<string>;

  farmStatus(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  farmVote(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  farmWeights(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getFarms(overrides?: CallOverrides): Promise<string[]>;

  getFarmsLength(overrides?: CallOverrides): Promise<BigNumber>;

  getFarmsWeights(overrides?: CallOverrides): Promise<BigNumber[]>;

  getWeightByUser(
    owner: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  lastVote(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  length(overrides?: CallOverrides): Promise<BigNumber>;

  lockFarm(overrides?: CallOverrides): Promise<string>;

  maxPercentage(overrides?: CallOverrides): Promise<BigNumber>;

  reset(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  resurrectFarm(
    _farm: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revote(
    _owner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setAdmin(
    _admin: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setConfiguration(
    _fnft: PromiseOrValue<string>,
    _hec: PromiseOrValue<string>,
    _lockFarm: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMaxPercentageFarm(
    _percentage: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setTestMode(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  totalWeight(overrides?: CallOverrides): Promise<BigNumber>;

  usedWeights(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  vote(
    _farmVote: PromiseOrValue<string>[],
    _weights: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  voteDelay(overrides?: CallOverrides): Promise<BigNumber>;

  votes(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    HEC(overrides?: CallOverrides): Promise<string>;

    addFarmForOwner(
      _farm: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    admin(overrides?: CallOverrides): Promise<string>;

    canVote(overrides?: CallOverrides): Promise<boolean>;

    deprecateFarm(
      _farm: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    fNFT(overrides?: CallOverrides): Promise<string>;

    farmStatus(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    farmVote(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    farmWeights(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFarms(overrides?: CallOverrides): Promise<string[]>;

    getFarmsLength(overrides?: CallOverrides): Promise<BigNumber>;

    getFarmsWeights(overrides?: CallOverrides): Promise<BigNumber[]>;

    getWeightByUser(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastVote(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    length(overrides?: CallOverrides): Promise<BigNumber>;

    lockFarm(overrides?: CallOverrides): Promise<string>;

    maxPercentage(overrides?: CallOverrides): Promise<BigNumber>;

    reset(overrides?: CallOverrides): Promise<void>;

    resurrectFarm(
      _farm: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    revote(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setAdmin(
      _admin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setConfiguration(
      _fnft: PromiseOrValue<string>,
      _hec: PromiseOrValue<string>,
      _lockFarm: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxPercentageFarm(
      _percentage: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setTestMode(overrides?: CallOverrides): Promise<void>;

    totalWeight(overrides?: CallOverrides): Promise<BigNumber>;

    usedWeights(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    vote(
      _farmVote: PromiseOrValue<string>[],
      _weights: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    voteDelay(overrides?: CallOverrides): Promise<BigNumber>;

    votes(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "FarmAddedByOwner(address)"(farm?: null): FarmAddedByOwnerEventFilter;
    FarmAddedByOwner(farm?: null): FarmAddedByOwnerEventFilter;

    "FarmDeprecated(address)"(farm?: null): FarmDeprecatedEventFilter;
    FarmDeprecated(farm?: null): FarmDeprecatedEventFilter;

    "FarmResurrected(address)"(farm?: null): FarmResurrectedEventFilter;
    FarmResurrected(farm?: null): FarmResurrectedEventFilter;

    "FarmVoted(address)"(owner?: null): FarmVotedEventFilter;
    FarmVoted(owner?: null): FarmVotedEventFilter;

    "SetAdmin(address,address)"(
      oldAdmin?: null,
      newAdmin?: null
    ): SetAdminEventFilter;
    SetAdmin(oldAdmin?: null, newAdmin?: null): SetAdminEventFilter;

    "SetConfiguration(address)"(admin?: null): SetConfigurationEventFilter;
    SetConfiguration(admin?: null): SetConfigurationEventFilter;

    "SetMaxPercentageFarm(uint256,address)"(
      percentage?: null,
      admin?: null
    ): SetMaxPercentageFarmEventFilter;
    SetMaxPercentageFarm(
      percentage?: null,
      admin?: null
    ): SetMaxPercentageFarmEventFilter;
  };

  estimateGas: {
    HEC(overrides?: CallOverrides): Promise<BigNumber>;

    addFarmForOwner(
      _farm: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    admin(overrides?: CallOverrides): Promise<BigNumber>;

    canVote(overrides?: CallOverrides): Promise<BigNumber>;

    deprecateFarm(
      _farm: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    fNFT(overrides?: CallOverrides): Promise<BigNumber>;

    farmStatus(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    farmVote(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    farmWeights(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFarms(overrides?: CallOverrides): Promise<BigNumber>;

    getFarmsLength(overrides?: CallOverrides): Promise<BigNumber>;

    getFarmsWeights(overrides?: CallOverrides): Promise<BigNumber>;

    getWeightByUser(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastVote(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    length(overrides?: CallOverrides): Promise<BigNumber>;

    lockFarm(overrides?: CallOverrides): Promise<BigNumber>;

    maxPercentage(overrides?: CallOverrides): Promise<BigNumber>;

    reset(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    resurrectFarm(
      _farm: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revote(
      _owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setAdmin(
      _admin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setConfiguration(
      _fnft: PromiseOrValue<string>,
      _hec: PromiseOrValue<string>,
      _lockFarm: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMaxPercentageFarm(
      _percentage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setTestMode(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    totalWeight(overrides?: CallOverrides): Promise<BigNumber>;

    usedWeights(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    vote(
      _farmVote: PromiseOrValue<string>[],
      _weights: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    voteDelay(overrides?: CallOverrides): Promise<BigNumber>;

    votes(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    HEC(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addFarmForOwner(
      _farm: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    admin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    canVote(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deprecateFarm(
      _farm: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    fNFT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    farmStatus(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    farmVote(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    farmWeights(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFarms(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFarmsLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFarmsWeights(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getWeightByUser(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lastVote(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    length(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lockFarm(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    maxPercentage(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    reset(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    resurrectFarm(
      _farm: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revote(
      _owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setAdmin(
      _admin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setConfiguration(
      _fnft: PromiseOrValue<string>,
      _hec: PromiseOrValue<string>,
      _lockFarm: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMaxPercentageFarm(
      _percentage: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setTestMode(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    totalWeight(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    usedWeights(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    vote(
      _farmVote: PromiseOrValue<string>[],
      _weights: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    voteDelay(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    votes(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
