/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { IERC20 } from "./@openzeppelin/contracts/token/ERC20/IERC20";
export { IERC20__factory } from "./factories/@openzeppelin/contracts/token/ERC20/IERC20__factory";
export type { FNFT } from "./contracts/VotingFarm.sol/FNFT";
export { FNFT__factory } from "./factories/contracts/VotingFarm.sol/FNFT__factory";
export type { LockFarm } from "./contracts/VotingFarm.sol/LockFarm";
export { LockFarm__factory } from "./factories/contracts/VotingFarm.sol/LockFarm__factory";
export type { VotingFarm } from "./contracts/VotingFarm.sol/VotingFarm";
export { VotingFarm__factory } from "./factories/contracts/VotingFarm.sol/VotingFarm__factory";
