/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  FNFT,
  FNFTInterface,
} from "../../../contracts/VotingFarm.sol/FNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "tokenOfOwnerByIndex",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class FNFT__factory {
  static readonly abi = _abi;
  static createInterface(): FNFTInterface {
    return new utils.Interface(_abi) as FNFTInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): FNFT {
    return new Contract(address, _abi, signerOrProvider) as FNFT;
  }
}
