/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  LockFarm,
  LockFarmInterface,
} from "../../../contracts/VotingFarm.sol/LockFarm";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "fnfts",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class LockFarm__factory {
  static readonly abi = _abi;
  static createInterface(): LockFarmInterface {
    return new utils.Interface(_abi) as LockFarmInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LockFarm {
    return new Contract(address, _abi, signerOrProvider) as LockFarm;
  }
}
