/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  SpookyLP,
  SpookyLPInterface,
} from "../../../contracts/VotingFarm.sol/SpookyLP";

const _abi = [
  {
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token0",
    outputs: [
      {
        internalType: "address",
        name: "token0",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token1",
    outputs: [
      {
        internalType: "address",
        name: "token1",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class SpookyLP__factory {
  static readonly abi = _abi;
  static createInterface(): SpookyLPInterface {
    return new utils.Interface(_abi) as SpookyLPInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SpookyLP {
    return new Contract(address, _abi, signerOrProvider) as SpookyLP;
  }
}
